### ISSUE TITLE
HubCallerContext.GetHttpContext returns null

### ISSUE THREAD

**Issue by mjrousos** [aspnet/AzureSignalR-samples#21] opened 2018-05-17 18:38 UTC
**Expected Behavior**
When using (non-Azure) SignalR for ASP.NET Core, my hub's `OnConnectedAsync` method was using `Context.GetHttpContext()` to get the HTTP context for the SignalR connection in order to view query strings from the client's connection request (and made client grouping decisions based on that data).

**Actual Behavior**
Using Azure SignalR as a Service, my hub receives `OnConnectedAsync` calls as expected, but `Context.GetHttpContext()` returns null.

**More Details**

Client code creating the SignalR connection:
```js
var connection = new signalR.HubConnectionBuilder()
    .withUrl(connectionUrl + '?gameId=' + gameId)
    .build();
```

Resulting calls using (non-Azure) SignalR:
```
OPTIONS http://localhost:5002/game/negotiate?gameId=M1pdnjc5
POST http://localhost:5002/game/negotiate?gameId=M1pdnjc5
GET http://localhost:5002/game?gameId=M1pdnjc5&id=f6pYCEmiObwaStHE0T2e9w
```

Resulting calls using ASRS:
```
OPTIONS http://localhost:5002/game/negotiate?gameId=6ljoK2lS
POST http://localhost:5002/game/negotiate?gameId=6ljoK2lS
OPTIONS https://mikerou-chat.service.signalr.net:5001/client/negotiate?hub=gamehub
POST https://mikerou-chat.service.signalr.net:5001/client/negotiate?hub=gamehub
GET https://mikerou-chat.service.signalr.net:5001/client/?hub=gamehub&id=aSnwi0uP6EJrbo9AW2CG8w&access_token=<JwtToken>
```

**Comment by davidfowl** [comment] 2018-05-17 19:01
Unfortunately this will never work to full fidelity. What things are you thing to access from the http context?

**Comment by davidfowl** [comment] 2018-05-17 19:02
We can probably flow query string and some headers

**Comment by xscript** [comment] 2018-05-29 08:08
Duplicate of https://github.com/Azure/azure-signalr/issues/108
Close this one and track with the above issue.

**Closed by xscript** 2018-05-29 08:08 UTC
